ARG ECT_VERSION=v0.9.3

FROM alpine/git AS checkout
RUN mkdir /ect && cd /ect && git clone --recurse-submodules --branch v0.9.3 https://github.com/fhanau/Efficient-Compression-Tool.git

FROM debian:bullseye-slim AS build
COPY --from=checkout /ect/Efficient-Compression-Tool /ect
RUN apt-get update && apt-get install -y make gcc cmake nasm g++ binutils-x86-64-linux-gnu \
    && cd /ect && mkdir build \
    && cd build && cmake ../src \
    && VERBOSE=1 make \
    && strip /ect/build/ect

FROM debian:bullseye-slim AS prod
RUN apt-get update && apt-get upgrade -y

COPY --from=build --chmod=755 /ect/build/ect /opt/ect
COPY --from=build /ect/licenses /opt/licenses

ENV PATH="${PATH}:/opt"

CMD ["/opt/ect"]
